# Generated by Django 5.1.7 on 2025-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("manufacturer_name", models.CharField(max_length=255)),
                ("pack_size_label", models.CharField(max_length=100)),
                ("salt_composition", models.TextField()),
                ("habit_forming", models.CharField(max_length=50)),
                ("therapeutic_class", models.CharField(max_length=100)),
                ("use0", models.CharField(max_length=255)),
                ("side_effects", models.TextField()),
                ("image_url_y", models.URLField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
