# Generated by Django 5.1.7 on 2025-04-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Medicine",
        ),
    ]
